repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      # - id: check-added-large-files
      - id: check-yaml
  - repo: local
    hooks:
      - id: youtube-link-to-iframe
        name: YouTube Link to Iframe
        entry: python bin/yt-link-to-iframe.py
        files: \.(md)$
        types: [markdown]
        language: python
        exclude: \.git.*
  - repo: https://github.com/shssoichiro/oxipng
    rev: v8.0.0
    hooks:
      - id: oxipng
        args: ["-o", "6"]
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.33.0
  #   hooks:
  #     - id: markdownlint
  #       args: ["--fix"]
